### ISSUE TITLE
Manifest won't download/stuck

### ISSUE THREAD

**Issue by TheN001** [ProjectSakura/android#18]
wanted to download the manifest, it got to a certain point after some fatal errors and it got stuck there. tried re-running it multiple times, always gets stuck at the same point. here are the errors and where it got stuck
![image](https://user-images.githubusercontent.com/53063352/192143158-4e64aff5-30c7-441e-8e9d-5ac7b61b7d23.png)

**Comment by mscottwvc** [comment]
I think some packages are missing at the end, specifically: https://github.com/PixelExperience/android_hardware_qcom_display/ doesnt seem to exist now.

**Comment by TheN001** [comment]
thats strange

**Comment by mscottwvc** [comment]
Thats what I see, when it gets stuck try hitting enter, it should give you a git pasword prompt, then if you hit enter again you see the repo failure and it will prompt for a git user name.

**Comment by TheN001** [comment]
then i put in my username and the key?

**Comment by mscottwvc** [comment]
No it won't work.  I think its just asking for the user name and password because the repo doesn't exist or is password protected.

**Comment by TheN001** [comment]
ah. well ill try it soon, i dont have a good enough pc to do anything on rn

**Comment by MODCORNERS** [comment]
Im gonna try fix this later when i get chance and update u all

**Comment by MODEDGES** [comment]
I managed to get it to download id suggest deleting the files that cant work from manifiest and it should fix it for u

**Comment by TheN001** [comment]
kk, i'll download the whole manifest clean and try to build it when my ssd arrives. thx for fixing it :)

**Comment by MODEDGES** [comment]
> kk, i'll download the whole manifest clean and try to build it when my ssd arrives. thx for fixing it :)

Ill check again if it breaks i can fork it and try fix it just so you know project sakura is now called Catalyst Os and is on andrpid 13 too

**Comment by TheN001** [comment]
> > kk, i'll download the whole manifest clean and try to build it when my ssd arrives. thx for fixing it :)
> 
> Ill check again if it breaks i can fork it and try fix it just so you know project sakura is now called Catalyst Os and is on andrpid 13 too

cool name ngl. tho i cant make the a13 for my phone since vendor is broken iirc, so its a work in progress xd

**Comment by MODEDGES** [comment]
I guess that's true and I agree with you their

**Comment by TheN001** [comment]
hey, little update on the manifest fetching issue, seems like when i run it with the provided commands on the git for android 12 it gives me some errors for PE repos and some for LOS repos. i tried running it without any additional commands just the innit and repo sync clean, seems like its syncing perfectly so far. no idea why it was giving me the errors with the other options still. i'll post another comment if i run into any more issues with the repo since i got some free time on my hands rn. as for now, repo is still syncing, it will take a few hrs to finish

**Comment by TheN001** [comment]
nope, still getting the errors
![Screenshot_20230114_221447](https://user-images.githubusercontent.com/53063352/212497200-ff33d81b-3403-4f14-a4ce-d38ff2efd64c.png)

**Comment by TheN001** [comment]
some more screenshots

![Screenshot_20230114_221642](https://user-images.githubusercontent.com/53063352/212497316-cca6ead8-a9f0-4720-a17a-960ea3112f65.png)

![Screenshot_20230114_221700](https://user-images.githubusercontent.com/53063352/212497345-f5895a8c-7650-48ad-8c72-c1ad3dd3c366.png)


![Screenshot_20230114_221717](https://user-images.githubusercontent.com/53063352/212497354-36e60581-6f1b-4040-8fa8-3dee3c1fba00.png)

**Comment by LordShenron** [comment]
Hi guys, I will close this thread as manifest for 14 is live and all other branches are not supported.
