### ISSUE TITLE
Track of bugs on revisioned manifest (14)

### ISSUE THREAD

**Issue by ilhan-athn7** [ProjectSakura/android#19]
- vendor/addon directory not exist, getting error at generating bootanimation.
Workaround; 
`mkdir -p vendor/addons/prebuilt`
`ln -s ../../lineage/bootanimation vendor/addon/prebuilt/bootanimation`

- CalendarTests not found
Workaround;
`Exclude CalendarTests line from platform_testing/build/tasks/tests/platform_test_list.mk for now. `

- chromium-webview does not synced properly (and possibly few other dirs)
Workaround;
`cd external/chromium-webview/prebuilt/arm64`
`git lfs pull`

- `packages/apps/SetupWizard/res/values/colors.xml` have incorrect color declaration
Workaround;
`Correct line 11 and 25.`

- `packages/apps/Settings/res/xml/firmware_version.xml`, about_device_name not found.
Workaround;
`Temporarely use self defined string on line 48`

I might update this post if i find other bugs

**Comment by LordShenron** [comment]
Thanks for the issue update.
