### ISSUE TITLE
package R does not exit 

### ISSUE THREAD

**Issue by ghost** [ProjectSakura/android#20]
device/xiaomi/sky/parts/src/org/lineageos/settings/thermal/ThermalSettingsActivi
ty.java:23: error: cannot find symbol
import com.android.settingslib.widget.R;

symbol:   class R
  location: package com.android.settingslib.widget
device/xiaomi/sky/parts/src/org/lineageos/settings/thermal/ThermalSettingsActivi
ty.java:32: error: package R does not exist
        getFragmentManager().beginTransaction().replace(R.id.content_frame,
                                                         ^

**Comment by LordShenron** [comment]
As you can see, this is clearly happening in your own device tree. You will need to adapt it as per qpr2 changes and there are plenty of repo on github to refer to.
